name: history_metallum
description: A new Flutter project for competitive exams.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  provider: ^6.0.5
  percent_indicator: ^4.2.3
  
  # YAH HAI SABSE ZAROORI LINE JO MISSING THI
  csv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  # Yh line bhi zaroori hai
  assets:
    - assets/
