name: history_metallum
description: A new Flutter project for competitive exams.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Yh packages app ko sundar aur functional banate hai
  cupertino_icons: ^1.0.2
  go_router: ^10.0.0
  provider: ^6.0.5
  # Sundar UI ke liye
  lottie: ^2.6.0
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
