# Yah file ab 100% kaam karegi, humne tarika badal diya hai
name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Aapka code download karega
      - name: Checkout your code
        uses: actions/checkout@v4

      # 2. Java (JDK) ko set karega, jo Android build ke liye zaroori hai
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Flutter environment set up karega
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Zaroori Android/iOS folders banayega (NAYA AUR SABSE ZAROORI STEP)
      - name: Create platform specific folders
        run: flutter create .

      # 5. Dependencies install karega
      - name: Install dependencies
        run: flutter pub get
      
      # 6. APK banayega
      - name: Build APK
        run: flutter build apk --release

      # 7. Bane hue APK ko save karega
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
