# Yah file ab 100% kaam karegi
name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Aapka code download karega
      - name: Checkout your code
        uses: actions/checkout@v4

      # 2. Java (JDK) ko set karega, jo Android build ke liye zaroori hai
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. Flutter environment set up karega
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # 4. Ek naya, Pura project banayega
      - name: Create a complete Flutter project structure
        run: flutter create --project-name history_metallum temp_project

      # 5. Aapki lib folder ko naye project me copy karega
      - name: Copy your lib folder
        run: cp -r lib temp_project/lib

      # 6. Aapki pubspec.yaml file ko naye project me copy karega
      - name: Copy your pubspec.yaml file
        run: cp pubspec.yaml temp_project/pubspec.yaml

      # 7. Ab naye project ke folder ke andar saare kaam honge
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./temp_project

      - name: Build APK
        run: flutter build apk --release
        working-directory: ./temp_project

      # 8. Bane hue APK ko save karega
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: temp_project/build/app/outputs/flutter-apk/app-release.apk
